name: Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_SHEET_KEY }} 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  

      - name: Set up Node.js 20
        uses: actions/setup-node@v3  
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install
          npm audit fix --force   # Try fixing potential dependency issues

      - name: Build with Parcel
        run: |
          parcel build index.html --no-source-maps
        continue-on-error: true  # Allow the build to continue even if this step fails
