name: Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_SHEET_KEY }} 
    steps:
      - name: Install dependencies
        run: npm install

      - name: Build with Parcel
        run: parcel build index.html --no-source-maps
